data_folder: "/fundus/data"
raw_data_folder:  "/media/morikawa/DataHDD/home/data/segmentation/fundus_dofe/Fundus_row"
task: "fundus"


dataset:
  train: /media/morikawa/DataHDD/home/data/segmentation/fundus_dofe/semi/domain_generalization
  test: /media/morikawa/DataHDD/home/data/segmentation/fundus_dofe/semi/domain_generalization
  resize:
    height: 256
    width: 256
  mean: [0.,0.,0.]
  std: [1.,1.,1.]
  seed: 42
  fillcolor: 255

model:
  torch_room: /media/morikawa/DataHDD/home/project/semi/domain_generalization/models
  pretrained: True
  drop_rate: 0
  num_classes: 2
  num_channels: 3
  
train:
  device: null
  gpu_exclude: []
  eval_interval: 500
  test_interval: 1000
  test_start: 10000
  use_CMSL: False
  checkpoint_dir: /media/morikawa/DataHDD/home/data/segmentation/fundus_dofe/semi/domain_generalization/checkpoints/
  resume_path: null
  batch_size: 16
  num_workers: 8
  max_epoch: null
  # max_iter will be determined by local_iter and rounds, even if max_epoch is set
  max_iter: 40000
  # optimizer: 
  #   lr: 1.0e-4
  #   beta1: 0.9
  #   beta2: 0.9999
  #   weight_decay: 5.0e-4
  optimizer: 
    lr: 1.0e-2
    momentum: 0.9
    weight_decay: 1.0e-4
  lr_scheduler:
    factor: 0.1
    patience: 2
    min_lr: 1.0e-7
  ema_decay: 0.999
  ema: False
  pseudo_label_threshold: 0.95
  lambda_u: 1.0

eval: 
  target_dir: /media/morikawa/DataHDD/home/data/segmentation/fundus_dofe/semi/domain_generalization/

wandb:
  key: ""
  project: "Fundus"
  run_name: ""

local:
  eval_interval: 200
  eval_start: 200
  save_interval: 500
  save_start: 19000

hooks:
  wandb: True
  
